plugins {
    id "com.android.application"
}

android {
    namespace "com.chanooh.hooksim"
    compileSdk 35

    defaultConfig {
        applicationId "com.chanooh.hooksim"
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly "io.github.libxposed:api:101.0.1"
}
